[general]
profile_img_url=http://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/QuantumultX.png
dns_exclusion_list=*.cmpassport.com, *.jegott5g.com, *.chinaunicom.cn
excluded_routes=192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 224.0.0.0/4
network_check_url=http://www.apple.com/library/test/success.html
server_check_url=http://www.gstatic.com/generate_204

[dns]
no_ipv6=true
prefer_ipv6=false
server=223.5.5.5
server=119.29.29.29
server=1.1.1.1
server=8.8.8.8

[policy]
url_test=自动选择, url=http://www.gstatic.com/generate_204, interval=300, tolerance=50
static=节点选择, 自动选择, DIRECT
static=国外媒体, 节点选择, 自动选择, DIRECT
static=港台陆影视, DIRECT, 节点选择
static=电报消息, 节点选择, DIRECT
static=苹果服务, DIRECT, 节点选择
static=广告拦截, REJECT, DIRECT

[filter_remote]
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/reject.snippet, tag=Loyalsoldier 广告拦截, opt-parser=false, enabled=true, force-policy=广告拦截
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/proxy.snippet, tag=Loyalsoldier 国外媒体, opt-parser=false, enabled=true, force-policy=国外媒体
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/direct.snippet, tag=Loyalsoldier 国内直连, opt-parser=false, enabled=true, force-policy=DIRECT
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/telegram.snippet, tag=Loyalsoldier Telegram, opt-parser=false, enabled=true, force-policy=电报消息
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/apple.snippet, tag=Loyalsoldier Apple 服务, opt-parser=false, enabled=true, force-policy=苹果服务
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/geoip-cn.snippet, tag=GeoIP China, opt-parser=false, enabled=true, force-policy=DIRECT

[rewrite_remote]
https://raw.githubusercontent.com/ddgksf2013/rewrite/master/AdBlock/AdBlock.conf, tag=墨鱼去广告重写, enabled=true
https://raw.githubusercontent.com/chavyleung/functional/master/env/boxjs.rewrite.quantumultx.conf, tag=BoxJS 脚本数据管理, enabled=true

[mitm]
hostname = *.pay.weixin.qq.com, *.tenpay.com, *.alipay.com, *.alipayobjects.com, *.jd.com, *.pinduoduo.com
