[general]
profile_img_url = https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/QuantumultX.png
resource_parser_url = https://raw.githubusercontent.com/crossutility/Quantumult-X/master/resource-parser.js
network_check_url = http://www.apple.com/library/test/success.html
server_check_url = http://www.gstatic.com/generate_204
dns_exclusion_list = *.cmpassport.com, *.jegott5g.com, *.chinaunicom.cn, id6.me
excluded_routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 224.0.0.0/4

[dns]
no-ipv6
server = 223.5.5.5
server = 119.29.29.29
server = 1.1.1.1
server = 8.8.8.8
doh-server = https://dns.alidns.com/dns-query

[policy]
static = 节点选择, DIRECT, 自动选择, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png
url-latency-benchmark = 自动选择, resource-tag-regex=.*, check-interval=600, tolerance=50, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png
static = 国外媒体, 节点选择, 自动选择, DIRECT, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png
static = 港台陆影视, DIRECT, 节点选择, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Bilibili.png
static = 电报消息, 节点选择, 自动选择, DIRECT, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
static = 苹果服务, DIRECT, 节点选择, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png
static = 广告拦截, REJECT, DIRECT, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Advertising.png
static = 漏网之鱼, 节点选择, DIRECT, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png

[server_remote]

[server_local]

[filter_remote]
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/reject.snippet, tag=Loyalsoldier 广告拦截, force-policy=广告拦截, enabled=true
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/proxy.snippet, tag=Loyalsoldier 国外媒体, force-policy=国外媒体, enabled=true
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/telegram.snippet, tag=Loyalsoldier Telegram, force-policy=电报消息, enabled=true
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/apple.snippet, tag=Loyalsoldier Apple服务, force-policy=苹果服务, enabled=true
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/direct.snippet, tag=Loyalsoldier 国内直连, force-policy=DIRECT, enabled=true
https://raw.githubusercontent.com/Loyalsoldier/quantumult-x-rules/release/geoip-cn.snippet, tag=Loyalsoldier GeoIP China, force-policy=DIRECT, enabled=true

[filter_local]
final, 漏网之鱼

[rewrite_remote]
https://raw.githubusercontent.com/ddgksf2013/rewrite/master/AdBlock/AdBlock.conf, tag=墨鱼去广告重写, enabled=true
https://raw.githubusercontent.com/chavyleung/functional/master/env/boxjs.rewrite.quantumultx.conf, tag=BoxJS 脚本数据管理, enabled=true

[rewrite_local]

[task_local]

[mitm]
hostname = *.pay.weixin.qq.com, *.tenpay.com, *.alipay.com, *.alipayobjects.com, *.jd.com, *.pinduoduo.com
